version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    env_file:
      - .env.local

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb_admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb
    env_file:
      - .env.local
